# Site settings
title: DataHacks
email: idoivri@gmail.com 
baseurl: '/datahacksweb'
description: "A website for the DataHacks hackathon, Nov 2015."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#00b0b7'
  links: '#219ab3'

# Footer settings
footer: DataHacks

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
